### ISSUE TITLE
关于ImageMagick

### ISSUE THREAD

**Issue by lsy-sunny** [DIG-Beihang/AISafety#16]
在运行test中的代码时，出现下面的错误：
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\AIsafety\lib\site-packages\wand\api.py", line 137, in <module>
    libraries = load_library()
  File "D:\ProgramData\Anaconda3\envs\AIsafety\lib\site-packages\wand\api.py", line 126, in load_library
    raise IOError('cannot find library; tried paths: ' + repr(tried_paths))
OSError: cannot find library; tried paths: []

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testimport.py", line 16, in <module>
    from EvalBox.Analysis.evaluation_base import Evaluation_Base
  File "E:\pycode\pycharmCode\AISafety\test/..\EvalBox\Analysis\evaluation_base.py", line 25, in <module>
    from EvalBox.Attack.CorAttack.corrupt import CORRUPT
  File "E:\pycode\pycharmCode\AISafety\test/..\EvalBox\Attack\CorAttack\__init__.py", line 5, in <module>
    from .corruptions import *
  File "E:\pycode\pycharmCode\AISafety\test/..\EvalBox\Attack\CorAttack\corruptions.py", line 17, in <module>
    import wand.color as WandColor
  File "D:\ProgramData\Anaconda3\envs\AIsafety\lib\site-packages\wand\color.py", line 10, in <module>
    from .api import library
  File "D:\ProgramData\Anaconda3\envs\AIsafety\lib\site-packages\wand\api.py", line 163, in <module>
    'Try to install:\n  ' + msg)
ImportError: MagickWand shared library not found.
You probably had not installed ImageMagick library.
Try to install:
  http://docs.wand-py.org/en/latest/guide/install.html#install-imagemagick-on-windows

**Comment by ZhanJ9** [comment]
我也遇到了同样的问题，请问您是怎么解决的
